### PR TITLE
Added base for translations and a more flexable UI

### PR DESCRIPTION
**Pull request by bartdebever**
Not every element is translated yet, there will be a project board item for this.
This should serve as a guideline on how translations will be done in the future and allows others to work on their language.

### CODE REVIEW

**Comment by StijnOostdam** [comment]
Please do translate everything before merging this PR. What is the status?

**Comment by bartdebever** [comment]
@StijnOostdam only the enum values used to add triggers and the custom effects.

**Comment by StijnOostdam** [comment]
Please update this branch with the latest changes on master

**Comment by StijnOostdam** [comment]
Fixed all missing translations and added enum translations. We will not translate effect names since they are identifiers.

**Pull request merged**
